sudo: required

services:
- docker

language: go

go:
- 1.12

go_import_path: github.com/mnadeem/volume_exporter

before_script:
  - docker --version
  - make init

script:
  - make

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  make docker;
  make push;
  fi