sudo: required

services:
- docker

language: go

go:
- 1.12

script:
  - make style
  - make vet
  - make gometalinter
  - make build

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  make docker;
  make push;
  fi
- if [[ -n "$TRAVIS_TAG" ]]; then
  make crossbuild release;
  fi